-- Excluir as tabelas caso elas já existam
DROP TABLE IF EXISTS MONI_HORARIO;
DROP TABLE IF EXISTS MONI_DISCIPLINA_CURSO;
DROP TABLE IF EXISTS MONI_MONITOR_DISCIPLINA;
DROP TABLE IF EXISTS MONI_MONITOR;
DROP TABLE IF EXISTS MONI_USUARIO;
DROP TABLE IF EXISTS MONI_DISCIPLINA;
DROP TABLE IF EXISTS MONI_CURSO;

-- Criar o conjunto de tabelas
CREATE TABLE MONI_USUARIO(
	ID_USUARIO integer PRIMARY KEY auto_increment,
    USUARIO varchar(8) not null unique,
    SENHA varchar(256) not null,
    CONFIRMADO boolean not null DEFAULT 0
);

CREATE TABLE MONI_MONITOR(
	ID_MONITOR integer PRIMARY KEY auto_increment,
    NOME varchar(60) not null,
    SOBRENOME varchar(60) not null,
    MATRICULA varchar(8) not null unique,
    EMAIL varchar(60) unique,
    TELEFONE varchar(11) unique,
    CURSO varchar(60) not null,
    FASE varchar(60),
    ID_USUARIO integer not null,
    CONSTRAINT fk_USUARIO_MONITOR FOREIGN KEY (ID_USUARIO) REFERENCES MONI_USUARIO(ID_USUARIO)
);

CREATE TABLE MONI_DISCIPLINA(
	ID_DISCIPLINA int PRIMARY KEY auto_increment,
    CODIGO varchar(8) not null unique,
    NOME varchar(60) not null
);

CREATE TABLE MONI_MONITOR_DISCIPLINA(
	ID_MONITOR_DISCIPLINA integer PRIMARY KEY auto_increment,
    ID_MONITOR integer not null,
    ID_DISCIPLINA integer not null,
    CONSTRAINT fk_MONITOR_DISCIPLINA_MONITOR FOREIGN KEY (ID_MONITOR) REFERENCES MONI_MONITOR(ID_MONITOR),
    CONSTRAINT fk_MONITOR_DISCIPLINA_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES MONI_DISCIPLINA(ID_DISCIPLINA)
);

CREATE TABLE MONI_CURSO(
	ID_CURSO integer PRIMARY KEY auto_increment,
    CODIGO varchar(3) not null,
    NOME varchar(60) not null,
    SIGLA varchar(5) not null
);

CREATE TABLE MONI_DISCIPLINA_CURSO(
	ID_DISCIPLINA_CURSO integer PRIMARY KEY auto_increment,
    ID_CURSO integer not null,
    ID_DISCIPLINA integer not null,
    FASE varchar(2) not null,
    CONSTRAINT fk_DISCIPLINA_CURSO_CURSO FOREIGN KEY (ID_CURSO) REFERENCES MONI_CURSO(ID_CURSO),
    CONSTRAINT fk_DISCIPLINA_CURSO_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES MONI_DISCIPLINA(ID_DISCIPLINA)
);

CREATE TABLE MONI_HORARIO(
	ID_HORARIO integer PRIMARY KEY auto_increment,
    INICIO time not null,
    FINAL time not null,
    DIA varchar(20) not null,
    ID_MONITOR integer not null,
    ID_DISCIPLINA integer not null,
    CONSTRAINT fk_HORARIO_MONITOR FOREIGN KEY (ID_MONITOR) REFERENCES MONI_MONITOR(ID_MONITOR),
    CONSTRAINT fk_HORARIO_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES MONI_DISCIPLINA(ID_DISCIPLINA)
);
