-- Inserts Cursos
INSERT INTO MONI_CURSO(CODIGO, NOME, SIGLA) VALUES("655", "Engenharia de Computação", "ENC");
INSERT INTO MONI_CURSO(CODIGO, NOME, SIGLA) VALUES("653", "Engenharia de Energia", "ENE");
INSERT INTO MONI_CURSO(CODIGO, NOME, SIGLA) VALUES("654", "Fisioterapia", "FISIO");
INSERT INTO MONI_CURSO(CODIGO, NOME, SIGLA) VALUES("656", "Medicina", "MED");
INSERT INTO MONI_CURSO(CODIGO, NOME, SIGLA) VALUES("652", "Tecnologias da Informação e Comunicação", "TIC");

-- Inserts Disciplinas INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("", "");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("CIT7139", "Programação em Computadores");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("CIT7203", "Informática na Educação I");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("CIT7224", "Gestão do Conhecimento");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("CIT7580", "Algoritmos e Programação");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("CIT7584", "Estrutura de Dados e Algoritmos");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("CIT7596", "Sistemas Multimídias");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("CIT7598", "Desenvolvimento de Sistemas Web");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7404", "Bases, Métodos e Técnicas de Avaliação");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7408", "Neurofisiologia");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7412", "Biologia Celular e Molecular");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7417", "Anatomia I");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7426", "Histologia e Embriologia");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7427", "Anatomia II");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7438", "Recursos Terapêuticos I");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7457", "Fisioterapia em Geriatria");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7458", "Cinesioterapia");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7461", "Fisioterapia em Cardiologia I");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7479", "Fisioterapia em Pedriatria II");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7480", "Fisioterapia em Pediatria I");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7489", "Fisioterapia em Cardiologia II");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS7496", "Fisiologia do Exercício");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS8203", "Módulo Sequencial II");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DCS8204", "Habilidades e Humanidades II");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DEC7125", "Estruturas de Dados I");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DEC7504", "Análise de Sinais e Sistemas Lineares");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DEC7536", "Projeto e Análise de Algoritmos");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("DEC7545", "Circuitos Elétricos para Computação");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7170", "Circuitos Elétricos");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7180", "Desenho Técnico");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7304", "Energia Solar Fotovoltaica");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7350", "Termodinâmica I");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7362", "Fundamentos de Química Orgânica");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7365", "Topografia e Geoprocessamento");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7366", "Termodinâmica II");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7367", "Teoria Eletromagnética");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7370", "Energia Eólica I");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7374", "Fundamentos de Controle");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("EES7378", "Eletrônica de Potência");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("FQM7101", "Cálculo I");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("FQM7102", "Cálculo II");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("FQM7103", "Geometria  Analítica");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("FQM7104", "Álgebra Linear");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("FQM7105", "Cálculo III");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("FQM7110", "Física A");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("FQM7113", "Química Geral");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("FQM7336", "Estática e Dinâmica");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("FQM7414", "Biofísica");
INSERT INTO MONI_DISCIPLINA(CODIGO, NOME) VALUES("FQM7420", "Bioquímica Básica");

-- Inserts Disciplinas-Cursos
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "TIC" AND b.CODIGO = "CIT7139";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "TIC" AND b.CODIGO = "CIT7203";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "05" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "TIC" AND b.CODIGO = "CIT7224";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "TIC" AND b.CODIGO = "CIT7580";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "03" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "TIC" AND b.CODIGO = "CIT7584";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "TIC" AND b.CODIGO = "CIT7596";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "05" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "TIC" AND b.CODIGO = "CIT7598";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "04" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7404";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7408";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7412";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7417";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7426";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7427";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "05" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7438";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "08" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7457";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "05" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7458";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "07" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7461";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "07" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7479";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "06" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7480";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "08" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7489";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "05" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "DCS7496";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "MED" AND b.CODIGO = "DCS8203";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "MED" AND b.CODIGO = "DCS8204";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "03" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "DEC7125";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "04" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "DEC7504";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "04" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "DEC7536";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "06" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "DEC7545";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "05" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7170";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "EES7180";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7180";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "08" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7304";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "04" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7350";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "03" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7362";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "04" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7365";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "05" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7366";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "05" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7367";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "06" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7370";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "07" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "EES7374";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "05" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7374";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "06" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "EES7378";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "FQM7101";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "FQM7101";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "FQM7102";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "FQM7102";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "FQM7103";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "FQM7103";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "FQM7104";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "FQM7104";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "03" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "FQM7105";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "03" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "FQM7105";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "FQM7110";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "FQM7110";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENC" AND b.CODIGO = "FQM7113";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "FQM7113";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "04" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "ENE" AND b.CODIGO = "FQM7336";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "01" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "FQM7414";
INSERT INTO MONI_DISCIPLINA_CURSO(ID_CURSO, ID_DISCIPLINA,  FASE)
SELECT a.ID_CURSO, b.ID_DISCIPLINA, "02" FROM MONI_CURSO a, MONI_DISCIPLINA b
WHERE a.SIGLA = "FISIO" AND b.CODIGO = "FQM7420";